spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spiritscribe
    username: spiritscribe
    password: spiritscribe
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus


