spring:
  application:
    name: spiritscribe-backend
  datasource:
    url: jdbc:postgresql://localhost:5433/spiritscribe
    username: spiritscribe
    password: spiritscribe
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
  data:
    redis:
      host: localhost
      port: 6379

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8080
  shutdown: graceful
  compression:
    enabled: true
    min-response-size: 2KB

cors:
  allowed-origins: "http://localhost:3000,https://dev.spiritscribe.com"
  allowed-methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
  allowed-headers: "Authorization,Content-Type,Accept"
  allow-credentials: true

security:
  jwt:
    issuer: spiritscribe
    audience: spiritscribe-users
    secret: change-me-in-prod
    access-token-ttl-seconds: 3600

# OpenAPI/Swagger 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
  show-actuator: true
  packages-to-scan: com.spiritscribe

# Spring Boot Admin 설정
spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
        instance:
          service-url: http://localhost:8080


