spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/spiritscribe
    username: spiritscribe
    password: spiritscribe
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO
    org.springframework: INFO


